name: Master Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Clippy
      run: |
        rustup component add clippy
        cargo clippy --all-targets --all-features -- -D warnings
    - name: Build and test
      run: cargo test